### ISSUE TITLE
Adding `tex` snippets

### ISSUE THREAD

**Issue by EderSantana** [JarrodCTaylor/dotfiles#10]
Jarrod,

I tried to add tex/latex snippets to UltiSnips creating a `tex.snippets` file with no success. Do you have any suggestions or guidances on how to do that?

Best,
-eder

**Comment by JarrodCTaylor** [comment]
Adding snippets has a few parts. I made a gist to try to help explain how to get them to work. 

Give https://gist.github.com/JarrodCTaylor/6d95bb739f0e297fd7d8 a try and see if you can get them wired up properly.

Let me know if that doesn't help.

**Comment by EderSantana** [comment]
I didn't work for me. If I add the snippet to the existing coffee.snippet file, it will show up, but creating new files didn't work. Also, I tried putting the tex.snippets file in the original UltiSnips folder and it didn't work. Do I have to update the plugin somehow?

**Comment by TayHobbs** [comment]
You want to place the custom snippets in the custom_config/custom-snips directory, you need a snip-link.sh and a snip-link.vim like in Jarrod's gist and like I have done here: https://github.com/TayHobbs/dotfiles_custom_config

**Comment by JarrodCTaylor** [comment]
I am going to close this one. The solutions presented have worked on multiple machines with running various OS. If you get stuck on a specific step you can open another issue with an example and we can try to help.
