### ISSUE TITLE
tmux 2.0 - unknown option: window-status-content

### ISSUE THREAD

**Issue by dustinfarris** [JarrodCTaylor/dotfiles#11]
In the default tmux config, tmux 2.0 seems to not like these directives:

https://github.com/JarrodCTaylor/dotfiles/blob/master/mac-tmux/themes/default.tmux#L37-L39

**Comment by JarrodCTaylor** [comment]
I will take a look at this eventually. However, currently I am on tmux 1.9a which is working without any issue. Are there any compelling features in 2.0 that would make updating now worth the time (I haven't really looked)?

**Comment by dustinfarris** [comment]
Nothing compelling, other than it is the version being installed by homebrew.  :-)

**Comment by JarrodCTaylor** [comment]
Reasonable point. I'm out of town this week with major time commitments. I will put this on the list of things to look into, but it might be a week before I can get to it.

**Comment by JarrodCTaylor** [comment]
So my brew was a little out of date ha. I have finally removed those lines to silence the 2.0 deprecation warnings.

**Comment by dustinfarris** [comment]
:+1: this make me happy.  Thanks.
