### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by mattjmorrison** [JarrodCTaylor/dotfiles#12]
Add stuff to the readme about opening the help in VIM

**Comment by JarrodCTaylor** [comment]
Already there.

<img width="744" alt="screen shot 2015-07-28 at 4 41 15 pm" src="https://cloud.githubusercontent.com/assets/4416952/8944673/9134efd2-3547-11e5-83b2-75b378a39d37.png">

**Comment by mattjmorrison** [comment]
Maybe somebody needs to RTFM before opening issues...
