### ISSUE TITLE
Feature Request: Display Server Info next to directory name

### ISSUE THREAD

**Issue by drbyronw** [JarrodCTaylor/dotfiles#21]
Not sure if this is the place, but it would be great feature to have a the name of the server that you're on displayed next to the directory name - would be useful in cases where you log into multiple machines (via ssh) or use different computers as part of your normal workflow.

**Comment by JarrodCTaylor** [comment]
Thanks for the suggestion, and although some could possibly find the server name useful in that specific scenario I don't believe it is a general purpose enough feature to add it to the prompt. It would provide no benefit and take up valuable real estate on a laptop screen if the majority of your time is spent developing locally on your own machine for example. Perhaps naming the tmux tab `<tmux-leader>,` to the name of your server would be a more simple and on demand solution for helping to remember where you are.

**Comment by drbyronw** [comment]
I appreciate the tmux idea - thanks
