### ISSUE TITLE
Installing dein

### ISSUE THREAD

**Issue by dustinfarris** [JarrodCTaylor/dotfiles#25]
For some reason the script in OSX/install-packages.sh did not install dein for me (even though it appears it should).  I had to install it myself.

**Comment by JarrodCTaylor** [comment]
Humm.. It just did not run?  I think I have ran that script three times now and I had difficulty getting dein to install properly one of those times (the bash script installed it but it began to fail when I opened vim initially).  So I don't know if I am completely sold on dein as a package manager It seems to be a little over engineered. I may consider replacing it with plug when I find time.

**Comment by dustinfarris** [comment]
Yeah, I guess it didn't run.  Maybe because the folder ~/.dein didn't exist already.  I'll try again on a new computer later and report back.

**Comment by JarrodCTaylor** [comment]
Good deal let me know how it goes when you try again. You shouldn't need to manually create the `~/.dein` directory for it to work. The installer script _should_ take care of it.

**Comment by dustinfarris** [comment]
It was me, sort of.  I got the impression that `Y` was the default option at the install script prompt (since it is capitalized), and just pressed enter.

```
Dustins-iMac% zsh OSX/install-packages.sh
Install all the packages (Y/n) =>
Dustins-iMac%
```

nothing happened—i assumed that i already had all the packages.  Turns out there isn't a default option here:

```
Dustins-iMac% zsh OSX/install-packages.sh
Install all the packages (Y/n) => Y
It appears Homebrew is already installed.
...
Done.
Complete setup dein!
```
