### ISSUE TITLE
On upgrade from OS X 10.10 to 10.11

### ISSUE THREAD

**Issue by khornberg** [JarrodCTaylor/dotfiles#26]
c compiling was messed up on my machine. I found an issue on `pyenv` that said to run `xcode-select --install` which installed something and then compling worked again.

This fixed an initial issue with `vimproc` not being able to be built and then had cascading effects.

**Comment by JarrodCTaylor** [comment]
What's the deal here?

**Comment by khornberg** [comment]
Just wanting to leave a note the fix that worked for me for the next passer
by.

Kyle

**Comment by JarrodCTaylor** [comment]
Ahh ok then. Good find.
