### ISSUE TITLE
SunPy broke vim

### ISSUE THREAD

**Issue by laurelfarris** [JarrodCTaylor/dotfiles#28]
I installed SunPy on my mac (OSX El Capitan version 10.11.5) using > conda install sunpy, and it seems to have reset my path. For instance, the first error after typing > vi test.py gives "ImportError: no module named UltiSnips". Do you know if there is a way to fix this?

**Comment by JarrodCTaylor** [comment]
I have no experience with SunPy. The documentation says `SunPy installation is more about installing the whole scientific Python ecosystem than SunPy itself.` I'm afraid I don't know how to help you with this.

**Comment by laurelfarris** [comment]
Just had to reinstall vim (in case anyone has a similar issue). Thanks.
