### ISSUE TITLE
Need way to disable included vim plugins

### ISSUE THREAD

**Issue by dustinfarris** [JarrodCTaylor/dotfiles#29]
There isn't a good way to do this with the current dein script in vimrc.  — only way is to delete the files from vim/plugin-configs in cloned copy which feels dirty.

/cc @laurelfarris

**Comment by JarrodCTaylor** [comment]
Does this no longer work with dein? 

https://github.com/JarrodCTaylor/dotfiles/wiki/Removing-Vim-Plugins

**Comment by dustinfarris** [comment]
No it doesn't.

**Comment by dustinfarris** [comment]
Best I could find is `disable()` but I couldn't get it to work.

https://github.com/Shougo/dein.vim/blob/master/doc/dein.txt#L327-L331

**Comment by JarrodCTaylor** [comment]
I should be able to leverage the `disable()` function to get it working again.

**Comment by JarrodCTaylor** [comment]
https://github.com/JarrodCTaylor/dotfiles/commit/0f0e74b2de9eaad28cdbf991cd9a1fb09e892573 restores the exclude functionality demonstrated https://github.com/JarrodCTaylor/dotfiles/wiki/Removing-Vim-Plugins
