### ISSUE TITLE
Vim - Arrow Key Behavior

### ISSUE THREAD

**Issue by mattjmorrison** [JarrodCTaylor/dotfiles#33]
What are your thoughts on this....

I was looking at some tabular data in Vim today (MySQL output from the Vim executor plugin)... I had two rows highlighted and... actually.... check out the screenshot...

![image](https://cloud.githubusercontent.com/assets/150277/18520868/3f47c460-7a6f-11e6-9d9f-cfcce4c411c6.png)

I've got the vim pane on the right which is in the way of me being able to see the last column of my output - so I wanted to use the arrow keys to decrease the size of the right pane so that I could see all of the data in the left pane. What I discovered was that the arrow keys are not mapped in visual mode... so my question is.... how do you feel about mapping the arrow keys to be the same in visual as in normal mode?

P.S. I think the whole "picture is worth 1000 words" deal... if there was any doubt about the truth in that statement it was just proven here... that would have sucked to paint a word picture to explain.

**Comment by JarrodCTaylor** [comment]
I am not opposed. It will require writing some kind of a function though.  If it were mapped exactly the same as it is in normal mode then we would lose the visual selection. The function will need to determine what is visually selected resize the split and then reselect what had been selected previously.

**Comment by mattjmorrison** [comment]
ugh... that sounds gross.

**Comment by JarrodCTaylor** [comment]
People on the street are not high-fiving each other when they hear about it.

![1514379-980x](https://cloud.githubusercontent.com/assets/4416952/18528568/2c797250-7a8f-11e6-9992-3c1292c9bbaa.jpg)
