### ISSUE TITLE
clipboard issues with tmux / vim on MacOS Sierra

### ISSUE THREAD

**Issue by keathleydavidj** [JarrodCTaylor/dotfiles#36]
After installing this stack, with some minor custom config I was experiencing this issue.
After any attempt to copy with ```y``` in vim, pasting it back would fail.

[This issue seems related](https://github.com/tmux/tmux/issues/543)

The workaround I've gone with was installing 'reattach-to-user-namespace' per [this comment on above thread](https://github.com/tmux/tmux/issues/543#issuecomment-248980734)

iTerm2 Build 3.0.10
tmux v2.3
vim v8

**Comment by JarrodCTaylor** [comment]
Yes it appears that the `reattach-to-user-namespace` is again required. I haven't updated to Sierra yet so I hadn't bumped into it. I will push an update shortly.

**Comment by toranb** [comment]
@JarrodCTaylor @keathleydavidj I did the Sierra update over the weekend and it's true that under tmux the copy to clipboard stuff is broken ...

But doing a simple `brew install reattach-to-user-namespace` plus the following tmux.conf changes got me rolling

```
# copy paste time
set-option -g default-command "reattach-to-user-namespace -l zsh"

# -----------------------------------------------------------------------------
# Vim visual selection and yank when in copy mode
# -----------------------------------------------------------------------------
bind Space copy-mode
bind C-Space copy-mode
bind -t vi-copy v begin-selection
bind -t vi-copy y copy-selection
bind -t vi-copy Escape cancel

bind-key -t vi-copy v begin-selection
bind-key -t vi-copy y copy-pipe "reattach-to-user-namespace pbcopy"

unbind -t vi-copy Enter
bind-key -t vi-copy Enter copy-pipe "reattach-to-user-namespace pbcopy"
```

<img width="1186" alt="tmuxupdate" src="https://cloud.githubusercontent.com/assets/147411/20494112/186bfc24-afe1-11e6-9ed9-8fdbc3860f06.png">

**Comment by JarrodCTaylor** [comment]
Do one of you want to create a PR for this? I'm not currently running Sierra and cannot confirm the issue or the fix.

**Comment by toranb** [comment]
@JarrodCTaylor landed :)

https://github.com/JarrodCTaylor/dotfiles/pull/37/files

**Comment by JarrodCTaylor** [comment]
Closed by https://github.com/JarrodCTaylor/dotfiles/pull/37
