### ISSUE TITLE
WTF Jedi?

### ISSUE THREAD

**Issue by mattjmorrison** [JarrodCTaylor/dotfiles#41]
Any thoughts on why this would happen?

![image](https://cloud.githubusercontent.com/assets/150277/21403362/171b84ee-c782-11e6-8cb6-c559a927784c.png)

All that Jedi crap pops in after pressing the `,` after the `"projects.json"` and has to be manually deleted

**Comment by JarrodCTaylor** [comment]
Consistently? I have always had similar but random issues with that same thing. Typically rather infrequent.

**Comment by mattjmorrison** [comment]
Yes, consistently.

**Comment by JarrodCTaylor** [comment]
Is there any way you can make a small .vimrc and example file and open a Jedi issue? That has been an elusive bug for years.

**Comment by mattjmorrison** [comment]
.... maybe....?

**Comment by JarrodCTaylor** [comment]
Closing for now. Reopen if there is anything actionable.
