### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by mattjmorrison** [JarrodCTaylor/dotfiles#44]
I finally got a new machine so I'm on Mac OS now... I'm getting an error... is this something that you've already encountered?

when opening vim
```
Error detected while processing function ProcessList[5]..AddBundle:
line    1:
E121: Undefined variable: vim
E116: Invalid arguments for function plug#
E121: Undefined variable: jarrodctaylor
E116: Invalid arguments for function plug#
Press ENTER or type command to continue
```

**Comment by JarrodCTaylor** [comment]
You successfully ran `install-files.sh` and `create-symlinks.sh` then restarted the terminal and attempt to open Vim and receive the error?

**Comment by mattjmorrison** [comment]
correct... I successfully ran both the install & symlink scripts, opened vim - which on the first time it did it's plugin installs or whatever... and now when I open vim I get those errors...

**Comment by JarrodCTaylor** [comment]
Take a look at this guy: https://github.com/JarrodCTaylor/dotfiles/commit/69f64471b9f1190d657a8d727882f20c3331df65

**Comment by mattjmorrison** [comment]
ah, you know what... I bet that's it.... please hold....

**Comment by mattjmorrison** [comment]
that fixed it... thanks!
