### ISSUE TITLE
Adding new keys to unite menu

### ISSUE THREAD

**Issue by EderSantana** [JarrodCTaylor/dotfiles#6]
Hey Jarrod,

Some plugins already come with default keybindings, is there a way to add then to the |<space> menu without configuring the plugin-configs/*.vim file by hand?

Best,
-eder

**Comment by TayHobbs** [comment]
This is possible as long as you are adding the plugin through your custom_config/ directory.
You just have to define the menu options in the under  `Unite Keymap Menu Item(s)`.

I am doing it with one of my plugins here: https://github.com/TayHobbs/dotfiles_custom_config/blob/master/vim-vroom-plugin.vim

**Comment by JarrodCTaylor** [comment]
@EderSantana In addition to Taylor's method above you could define a file in your `custom-configs` directory just for menu items. Something like this

**custom-configs/menu-items.vim**
``` vim
let g:unite_source_menu_menus.CustomKeyMaps.command_candidates += [['➤ Your description goes here                                    <Leader>ui', 'normal <Leader>ui']]
let g:unite_source_menu_menus.CustomKeyMaps.command_candidates += [['➤ Another description goes here                                 <Leader>zx', 'normal <Leader>zx']]
```
